### ISSUE TITLE
CentOS Stream target?

### ISSUE THREAD

**Issue by truatpasteurdotfr** [NVIDIA/yum-packaging-precompiled-kmod#21]
hi,

Nice to  see you sharing your work.

Will you also target CentOS Stream as best effort since the pipeline might be suited for automation?

Thanks

Tru

**Comment by kmittman** [comment]
Hi @truatpasteurdotfr 
The RPM .spec files should be able to build on any RHEL-derivative. However, the precompiled kmod RPMs are kernel string specific, it must be the exact same kernel, i.e.  `4.18.0-305.7.1` to install and function.

As mentioned in this [blog post](https://developer.nvidia.com/blog/streamlining-nvidia-driver-deployment-on-rhel-8-with-modularity-streams/), at this time, our CI/CD automation is setup for RHEL 8 (x86_64) only.

Comparing the [list of _kernel-core_ packages for CentOS 8 Stream](http://mirror.centos.org/centos/8-stream/BaseOS/x86_64/os/Packages/) versus [list of _kernel-core_ packages for RHEL 8](https://developer.download.nvidia.com/compute/cuda/repos/rhel8/x86_64/precompiled/) there is sometimes overlap but in general not.

Therefore, I would suggest to either use the DKMS modularity streams or build your own precompiled kmod packages (as per the [README](https://github.com/NVIDIA/yum-packaging-precompiled-kmod#readme) or [Packaging Guide](https://github.com/NVIDIA/yum-packaging-nvidia-driver#Packaging-Guide)).

Closing. If you need help with building your own packages, feel free to re-open.
