### ISSUE TITLE
Update /fm profile

### ISSUE THREAD

**Issue by kmittman** [NVIDIA/yum-packaging-precompiled-kmod#22]
Need `genmodules.py` changes for the `/fm` modularity profile to address rename of fabric manager package from https://github.com/NVIDIA/yum-packaging-fabric-manager/pull/2

**Comment by zvonkok** [comment]
Ah great, this is what I was looking for, any ETA when this will land?

**Comment by kmittman** [comment]
Note: `465` branch is EOL. And `450` branch does not pick up these changes.
