### ISSUE TITLE
Screen blank after installing drivers

### ISSUE THREAD

**Issue by namupatel** [NVIDIA/yum-packaging-precompiled-kmod#29]
Thanks for simplifying driver installation process. Unfortunately my display is blank after the installation. I can log in remotely and successfully run nvidia-smi and execute CUDA scripts. I'm a bit of a newbie so guidance would be appreciated. 

NVIDIA driver version: 470.57.02
RHEL kernel version: 8.4
modularity stream: latest
modularity profile: default

**Comment by kmittman** [comment]
@namupatel it's been awhile so closing this. Feel free to re-open if you are still experiencing this issue.
