### ISSUE TITLE
kmod-nvidia-535.54.03-5.14.0-284.18.1-535.86.10-1.el9_2.x86_64.rpm is missing

### ISSUE THREAD

**Issue by alphacc** [NVIDIA/yum-packaging-precompiled-kmod#45]
From repo : 
http://developer.download.nvidia.com/compute/cuda/repos/rhel9/x86_64/

Latest kmod available is 
kmod-nvidia-535.54.03-5.14.0-284.18.1-535.54.03-3.el9_2.x86_64.rpm

It seems we are missing : 
kmod-nvidia-535.54.03-5.14.0-284.18.1-535.86.10-1.el9_2.x86_64.rpm

yum update cannot upgrade to *535*

**Comment by kmittman** [comment]
Okay @alphacc this has been resolved now for driver `535.86.10` available for the latest RHEL9 kernel `5.14.0-284.25.1` 
https://developer.download.nvidia.com/compute/cuda/repos/rhel9/x86_64/precompiled
